name: 02 - Eventos Issue
on:
    push:
        paths-ignore:
        - '*.md'
    issues:
        types:
        - opened
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: hola mundo
      run: echo "HELLO WORLD"
